jor-alv/toddlr-care

app/views/layouts/application.html.erb, config/environments/production.rb, config/initializers/devise.rb
Initial devise config, to be modified as soon as we obtain domain name
=> Initial devise config

db/seeds.rb
=> Testing the database

app/models/user.rb, db/seeds.rb
=> Modifies user model

app/models/daycare.rb, app/policies/daycare_policy.rb, db/migrate/20220524184428_create_daycares.rb, db/schema.rb, test/models/daycare_test.rb, test/policies/daycare_policy_test.rb
- adds daycare model, including all agreed columns
- protects new model with pundit
Where to see the changes:
- daycare model
- schema
- policies folder
@kimcoquilla
=> Adds daycare model

app/models/consultation.rb, app/policies/consultation_policy.rb, db/migrate/20220524190943_create_consultations.rb, test/models/consultation_test.rb, test/policies/consultation_policy_test.rb
- Adds consultation model, plus pundit protection
Where to see the changes:
- consultation model
- schema
- policies folder
@kimcoquilla
=> Adds consultation model

app/models/consultation.rb, app/models/daycare.rb, app/models/review.rb, app/models/user.rb, db/migrate/20220524193848_change_status_to_category_in_users.rb, db/migrate/20220524194243_add_references_to_reviews.rb, db/migrate/20220524200741_add_references_to_consultations.rb, db/migrate/20220524201055_add_references_to_daycares.rb, db/schema.rb
- Changes name of user model enum to category
- Adds foreign keys in reviews, consultations and daycares, in each case, modifying the name of the foreign ket that refers to the users to account for the different types of users
@kimcoquilla
=> Modifies schema and foreign keys

app/models/user.rb, db/schema.rb
Removes unnecessary validations
@kimcoquilla
=> Removes unnecessary validations

app/models/daycare.rb, app/models/daycare_tag.rb, app/models/tag.rb, db/migrate/20220524204955_create_tags.rb, db/migrate/20220524205724_create_daycare_tags.rb, db/schema.rb, test/models/daycare_tag_test.rb, test/models/tag_test.rb
Adds tag and daycare tag model
@jor-alv
=> Adds tag and daycare tag model

app/models/daycare.rb, app/models/tag.rb, app/models/user.rb, config/environments/production.rb, config/initializers/devise.rb
Adds additional associations
@kimcoquilla
=> Adds additional associations

app/controllers/profiles_controller.rb, test/controllers/profiles_controller_test.rb
What changed:
- Creates profiles controller
@jcampbell92
=> Generates Profiles Controller

config/routes.rb
Routing Daycares, Profiles, Reviews, Consultations
=> Routing done and validated by Stephane

app/controllers/daycares_controller.rb, app/views/daycares/show.html.erb
What changed
- Added Daycares show action and view
@kimcoquilla
=> Adds daycares show action and view

app/controllers/daycares_controller.rb
Changes to show action in daycares controller
=> Changes to show action in daycares controller

db/seeds.rb
Creates initial seeds with Faker
=> Adds initial Faker seeds

app/models/consultation.rb, app/models/review.rb
- Added class name in review and consultation models to correct syntax error
Where to see the changes:
- Review and Consultation models
@kimcoquilla
=> Models addition

Gemfile, Gemfile.lock, app/controllers/daycares_controller.rb, app/models/daycare.rb, app/views/layouts/application.html.erb, app/views/shared/_navbar.html.erb
=> PG search added in navbar

app/controllers/daycares_controller.rb, app/models/daycare.rb
=> Added description in PG search

db/seeds.rb
What has changed
- Creates structure and placeholders for users and daycares in the seeds file
@Driftmaster7
=> Working on seeds

app/models/review.rb, db/seeds.rb
Changes:
- Adds numericality validation for stars in the Review model
- Adds structure and placeholders for the Review seeds
- Adds structure and placeholders for the Consultation seeds
@kimcoquilla
=> Review model and seeds

db/seeds.rb
- Adds some Faker seeds for testing purposes
@Driftmaster7
=> Adds some Faker seeds for testing purposes

app/controllers/consultations_controller.rb, app/controllers/daycares_controller.rb, app/controllers/reviews_controller.rb, app/policies/review_policy.rb, app/views/daycares/index.html.erb, app/views/daycares/show.html.erb, test/controllers/reviews_controller_test.rb
=> As a parent we can add a review

app/controllers/reviews_controller.rb, app/policies/review_policy.rb, app/views/daycares/show.html.erb
@jor-alv 
Delete a review if you made the review
=> Delete a review if you made the review

Gemfile, Gemfile.lock, app/controllers/daycares_controller.rb, app/models/daycare.rb, app/views/daycares/edit.html.erb, app/views/daycares/new.html.erb, app/views/daycares/show.html.erb, app/views/layouts/application.html.erb, app/views/shared/_flashes.html.erb, config/environments/development.rb, config/storage.yml, db/migrate/20220527153520_create_active_storage_tables.active_storage.rb, db/schema.rb
added a cloudinary when you add a daycare..
added an edit a daycare with a pencil icon
=> Add cloudinary

app/views/layouts/application.html.erb
fix duplicate flash message
@jor-alv
=> fix duplicate flash message

app/controllers/daycares_controller.rb, app/views/daycares/show.html.erb, db/seeds.rb
What has changed
- Adds markers in daycares controller (show action)
- Adds seeds for demo
@Driftmaster7
=> Show map and seeds for demo

db/seeds.rb
Passwords for seeds
@kimcoquilla 
@Driftmaster7
=> Passwords for seeds

config/environments/production.rb
=> Activates Cloudinary

app/javascript/controllers/mapbox_controller.js
What has changed
- Adds initial styling to map, just for now
=> Initial map style

app/views/daycares/show.html.erb
=> fix the size of photo from cloudinary

app/views/daycares/show.html.erb
=> debug error daycare profile

app/views/daycares/show.html.erb
=> debug review when you are not log in

app/javascript/controllers/mapbox_controller.js
=> Resizes map markers

app/models/daycare.rb, app/views/daycares/_info_window.html.erb, app/views/daycares/edit.html.erb, app/views/daycares/new.html.erb, db/migrate/20220531141550_add_email_to_daycares.rb, db/migrate/20220531141659_add_phone_number_to_daycares.rb, db/schema.rb, db/seeds.rb
- Adds email and phone number columns to daycares table
- Adds validation for daycare emails
- Adds seeds for daycare emails and phone numbers
- Info now showing on infowindows
=> Map's info windows

db/seeds.rb
Adds opening dates to daycares
=> Added opening dates

Gemfile, Gemfile.lock, app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_calendar.scss, app/assets/stylesheets/components/_index.scss, app/controllers/consultations_controller.rb, app/controllers/profiles_controller.rb, app/views/daycares/show.html.erb, app/views/profiles/partials/_supplier-show.html.erb, app/views/profiles/partials/client-tabs/_all-tab.html.erb, app/views/profiles/partials/client-tabs/_confirmed-tab.html.erb, app/views/profiles/partials/client-tabs/_pending-tab.html.erb, app/views/profiles/partials/tabs/_confirmed-tab.html.erb, app/views/profiles/partials/tabs/_pending-tab.html.erb, app/views/simple_calendar/_calendar.html.erb, app/views/simple_calendar/_month_calendar.html.erb, app/views/simple_calendar/_week_calendar.html.erb, db/migrate/20220531161209_rename_datetime_to_starttime_in_consultations.rb, db/schema.rb, db/seeds.rb
=> Calendar book now

app/views/daycares/edit.html.erb, app/views/daycares/new.html.erb
@jor-alv 
added div container in new and edit form for daycare
added open date in the simple form
=> Daycare opening date

app/controllers/daycares_controller.rb, app/javascript/controllers/favorite_controller.js, app/policies/daycare_policy.rb, app/views/daycares/_like_button.html.erb, app/views/daycares/_toggle_favorite.js.erb, app/views/daycares/show.html.erb, config/routes.rb
Adds favorites functionality in daycares show page, including:
- new route
- bespoke method in the controller
- initial html code in the view
- new javascript controller
=> Favorites functionality

app/controllers/daycares_controller.rb, app/javascript/controllers/favorite_controller.js, app/javascript/controllers/show_controller.js, app/policies/daycare_policy.rb, app/views/daycares/_like_button.html.erb, app/views/daycares/_toggle_favorite.js.erb, app/views/daycares/show.html.erb
Continues work on favorites functionality, adds custom innerText to Favorites icon, users can no longer favorite daycares if they are not logged-in
=> Favorites functionality2

app/views/profiles/edit.html.erb
=> fix error in edit profile

db/seeds.rb
Adds address placeholders in user seeds
=> Adds address placeholders in user seeds

db/seeds.rb
=> Small change to user seeds

app/views/profiles/partials/_client-show.html.erb, app/views/profiles/partials/_supplier-show.html.erb
Edit profile btn to icon pencil
Fix some bugs in profile page
=> Edit profile icon pencil

app/views/daycares/show.html.erb
added a fixed value in simple form for number of children
fixed the looks for no reviews yet in daycare profile
@jor-alv
=> Debug consultation

app/views/profiles/partials/_client-show.html.erb, app/views/profiles/partials/_supplier-show.html.erb
=> Comments out delete link

app/views/daycares/index.html.erb
Adds daycare photos in index view
=> Adds daycare photos in index view

app/views/profiles/partials/tabs/_daycares-tab.html.erb
Adds photos of daycares in the owners profile
=> Adds photos of daycares in the owners profile
